# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

parameters:
- name: buildPhpVersion
  displayName: Build PHP version
  type: string
  default: 7.4
- name: buildImportTool
  displayName: Build import tools
  type: string
  default: csv
- name: platforms
  displayName: Build platforms
  type: string
  default: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
- name: repository
  displayName: Repository name to push to
  type: string
  default: jc5x/test-repository

jobs:
- job: Jobbie
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-16.04'
    name: Default
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      git config --global user.email "james@firefly-iii.org"
      git config --global user.name "James Cole"
    displayName: 'Do Git config'
  - script: |
      set -euo pipefail
      sudo rm -rf /var/lib/apt/lists/*
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
      sudo apt-get update
      sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

      echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
      mkdir -p $HOME/.docker
      touch $HOME/.docker/config.json
      echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
      sudo service docker restart

      echo "Docker username = '$(DOCKERUSERNAME)'."

      docker version -f '{{.Server.Experimental}}'
      docker version
    displayName: 'Verify Docker installation.'

  - script: |
      echo "Docker username = '$(DOCKERUSERNAME)'."
      whoami
      echo "I am $(whoami)"
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes i
      docker buildx create --name firefly_iii_builder
      docker buildx inspect firefly_iii_builder --bootstrap
      docker buildx use firefly_iii_builder
    displayName: 'Set up builder'

  - script: |
      cd ImportToolImage
      echo "Docker username = '$(DOCKERUSERNAME)'."
      echo $(DOCKERPASSWORD) | docker login --username $(DOCKERUSERNAME) --password-stdin
      #cd ${{ parameters.buildImageType }}-${{ parameters.buildPhpVersion }}/
      #docker buildx build --platform ${{ parameters.platforms }} -t ${{ parameters.repository }}:${{ parameters.buildImageType }}-${{ parameters.buildPhpVersion }} --push . -f Dockerfile
    displayName: 'Build!'

  - checkout: self
    clean: true